spring:
  profiles:
    active: boot
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600

server:
  # tomcat调优
  tomcat:
    uri-encoding: UTF-8
    # 服务器在任何给定时间接受和处理的最大连接数
    max-connections: 20000
    # 最大工作线程数
    max-threads: 1000
    # 最小工作线程数
    min-spare-threads: 200
  netty:
    connection-timeout:
    maxThreads: 500


zh:
  http:
    cors:
      enable: true
      # 不建议全部开放
      access-control-allow-origin: "*"
      access-control-allow-methods: POST, PUT, GET, OPTIONS, DELETE
      # 跨域请求如果有自定义的头需要在这里加上，或者用*
      access-control-allow-headers: Authorization, Content-Type, Origin, X-Requested-With, Accept
      access-control-max-age: 3600
    accept-language:
      # 请求国际化是否通过请求参数指定
      # request-param-lang：通过参数指定 - .../api?lang=zh_CN
      # header-accept-language: 通过头指定 - Accept-Language=zh_CN
      type: request-param-lang

  async:
    # 核心线程数会一直存在池中，优先级最高
    core-pool-size: 5
    # 队列容量，核心线程队列达到这个数量时才会新建线程，直到最大线程数满为止。
    queue-capacity: 30
    # 最大线程数，当核心线程全部队列满时才会新建线程，直到最大值
    max-pool-size: 50
    # 非核心线程活跃时间（秒），请严格控制在线程中运行的任务时间为毫秒级。
    keep-alive-seconds: 30
    # 线程名称前缀
    thread-name-prefix: Test-Async-Thread
    # 多少秒后中断线程的执行
    await-termination-seconds: 60
    # 拒绝策略: 即核心线程、最大线程都满且队列也都满的情况下走拒绝策略
    # 可选：AbortPolicy/DisCardPolicy/DisCardOldSetPolicy/CallerRunsPolicy
    rejected-execution-handler: CallerRunsPolicy

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.lemon:  DEBUG
