zh:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: qiniu
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://static.teysoft.com
      access-key: 9u1vrjfDJJUzcpI1f-0TggD25jC8lm-G4_wuUOJ3
      secret-key: oMnKjJWwaXVF7T4IyeFPcQf5qUDB6JJVbeV8tWQf
      bucket-name: teysoft
