mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_ # 全局逻辑删除字段值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 原生配置
  configuration:
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启Mybatis二级缓存，默认为 true。
    cache-enabled: true
  # 实体枚举扫描
  type-enums-package: mp.enums
  mapper-locations: classpath:/mapper/**.xml

zh:
  http:
    cors:
      enable: true
      access-control-allow-origin: "*"
      access-control-allow-methods: POST, PUT, GET, OPTIONS, DELETE
      access-control-allow-headers: Authorization, Content-Type
      access-control-max-age: 3600
    accept-language:
      # 请求国际化是否通过请求参数指定
      # request-param-lang：通过参数指定 - .../api?lang=zh_CN
      # header-accept-language: 通过头指定 - Accept-Language=zh_CN
      type: header-accept-language
  db:
    sequence:
      # 分布式ID的服务节点，如果不设置则根据服务器IP自动计算节点
      # 要么所有服务器都不设置，要指定就全部指定但不能重复
      # 范围：0-1023之间
      node-id: 100

jasypt:
  encryptor:
    # 必须有此配置
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    # 生产环境要去掉，将其放入运行参数中 -Djasypt.encryptor.password=你的盐
    password: salt2021

spring:
  profiles:
    active: boot
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  autoconfigure:
    # 使用mybatis的动态路由数据源必须排除druid的默认配置
    # DruidDataSourceAutoConfigure会注入一个DataSourceWrapper，其会在原生的spring.datasource下找url,username,password等。
    # 而我们动态数据源的配置路径是变化的。
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: tenant0-master
      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        # 普通非多租户的一主多从
#        master:
#          url: "ENC(9EBchHExdurIkG3qj95OcjzlcqTfjl6V40ygUZwL3A4ITKSfWWSFMQExgd/sVivYZg8GuOtBBBBggV7EpYhViRkdYRw3ZuYoas3yrzOBl/cPAQDsUzh1RgS4+DaJnE6PiQq5LMd7dxfGzfkbuuDU8brgXYNeX9UecoljFomtbSeW2jAuGyT4T6Zirj2RlxZT7FbjgQ5S/t+AJHCCGl+h3Z4aBTp1oHurEMeqoVibOIwONP1bdbnMKnH/Rx8in6klQJWCHvC51qxKmm8m2SQfoA==)"
#          driver-class-name:  com.mysql.jdbc.Driver
#          username: "ENC(2YPT4O9fdwNk+2kwWrzOs10hIFAb4Ok1f2Bb3oqe4AmnZT3HnOcRHuhB91LBvAKA)"
#          password: "ENC(q400Fvd/996XBHSGoZneYOF89p7nCZChLNBojpwmG97B/Nt9JZlAN2kJ1aw9gtet)"
#          druid: # 以下参数针对每个库可以重新设置druid参数
#            initial-size:  10
#            max-active:  50
#            min-idle:  10
#            max-wait:  60000
#            pool-prepared-statements:  true
#            max-pool-prepared-statement-per-connection-size:  20
#            validation-query:  SELECT 1 FROM DUAL
#            test-on-borrow:  false
#            test-on-return:  false
#            test-while-idle:  true
#            time-between-eviction-runs-millis:  60000
#            filters:  stat,wall
#        slave_1:
#          url: "ENC(9EBchHExdurIkG3qj95OcjzlcqTfjl6V40ygUZwL3A4ITKSfWWSFMQExgd/sVivYZg8GuOtBBBBggV7EpYhViRkdYRw3ZuYoas3yrzOBl/cPAQDsUzh1RgS4+DaJnE6PiQq5LMd7dxfGzfkbuuDU8brgXYNeX9UecoljFomtbSeW2jAuGyT4T6Zirj2RlxZT7FbjgQ5S/t+AJHCCGl+h3Z4aBTp1oHurEMeqoVibOIwONP1bdbnMKnH/Rx8in6klQJWCHvC51qxKmm8m2SQfoA==)"
#          driver-class-name:  com.mysql.jdbc.Driver
#          username: "ENC(2YPT4O9fdwNk+2kwWrzOs10hIFAb4Ok1f2Bb3oqe4AmnZT3HnOcRHuhB91LBvAKA)"
#          password: "ENC(q400Fvd/996XBHSGoZneYOF89p7nCZChLNBojpwmG97B/Nt9JZlAN2kJ1aw9gtet)"

        # 多租户主从数据源（高级）
        # 固定格式："tenant"+"租户ID"+"-分库数据源"+"_分组序号"
        tenant0-master:
          url: "ENC(9EBchHExdurIkG3qj95OcjzlcqTfjl6V40ygUZwL3A4ITKSfWWSFMQExgd/sVivYZg8GuOtBBBBggV7EpYhViRkdYRw3ZuYoas3yrzOBl/cPAQDsUzh1RgS4+DaJnE6PiQq5LMd7dxfGzfkbuuDU8brgXYNeX9UecoljFomtbSeW2jAuGyT4T6Zirj2RlxZT7FbjgQ5S/t+AJHCCGl+h3Z4aBTp1oHurEMeqoVibOIwONP1bdbnMKnH/Rx8in6klQJWCHvC51qxKmm8m2SQfoA==)"
          driver-class-name: com.mysql.jdbc.Driver
          username: "ENC(2YPT4O9fdwNk+2kwWrzOs10hIFAb4Ok1f2Bb3oqe4AmnZT3HnOcRHuhB91LBvAKA)"
          password: "ENC(q400Fvd/996XBHSGoZneYOF89p7nCZChLNBojpwmG97B/Nt9JZlAN2kJ1aw9gtet)"
        tenant100-master:
          url: "ENC(9EBchHExdurIkG3qj95OcjzlcqTfjl6V40ygUZwL3A4ITKSfWWSFMQExgd/sVivYZg8GuOtBBBBggV7EpYhViRkdYRw3ZuYoas3yrzOBl/cPAQDsUzh1RgS4+DaJnE6PiQq5LMd7dxfGzfkbuuDU8brgXYNeX9UecoljFomtbSeW2jAuGyT4T6Zirj2RlxZT7FbjgQ5S/t+AJHCCGl+h3Z4aBTp1oHurEMeqoVibOIwONP1bdbnMKnH/Rx8in6klQJWCHvC51qxKmm8m2SQfoA==)"
          driver-class-name: com.mysql.jdbc.Driver
          username: "ENC(2YPT4O9fdwNk+2kwWrzOs10hIFAb4Ok1f2Bb3oqe4AmnZT3HnOcRHuhB91LBvAKA)"
          password: "ENC(q400Fvd/996XBHSGoZneYOF89p7nCZChLNBojpwmG97B/Nt9JZlAN2kJ1aw9gtet)"
        tenant100-slave_1:
          url: "ENC(nmyyUxmkyUhsZNI42RBllwMAnR4TRYvKXgTIFKp/Rf2lXZZRoq1EcII7YvpJF1G10ku/7Ji0VgsiXwL+azzHO7xaxeZZrBpzBzhx0kKtNWKimlO7t8tuA4fhljd2MvnNDJ5fz0BOrprKYJPcEH2OImnyuglfZ3kp9efJdl8IdTkjK/cYtRwaCdwWnbHo3mcJN3V3DKUO2ZBuQSZbhU7sIThvV7wczUS6o+8y+TJjyiHIAsv/vfCPRjhsfnfGhE7MkTjRt9x3vEy+2fJMDiv0ow==)"
          driver-class-name: com.mysql.jdbc.Driver
          username: "ENC(2YPT4O9fdwNk+2kwWrzOs10hIFAb4Ok1f2Bb3oqe4AmnZT3HnOcRHuhB91LBvAKA)"
          password: "ENC(q400Fvd/996XBHSGoZneYOF89p7nCZChLNBojpwmG97B/Nt9JZlAN2kJ1aw9gtet)"
      druid:
        initial-size:  10
        max-active:  50
        min-idle:  10
        max-wait:  60000
        pool-prepared-statements:  true
        max-pool-prepared-statement-per-connection-size:  20
        validation-query:  SELECT 1 FROM DUAL
        test-on-borrow:  false
        test-on-return:  false
        test-while-idle:  true
        time-between-eviction-runs-millis:  60000
        filters:  stat,wall
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 67891234
logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.lemon:  DEBUG
